FROM consul:latest
RUN mkdir /scripts
RUN echo "" > /scripts/consul_watch.log
RUN chown consul:consul /scripts/consul_watch.log
COPY handler /scripts/
COPY config.json /consul/config/
RUN chmod +x /scripts/handler
